version: '3'
services:
  db:
    image: postgres:15.8
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: Hastex
      POSTGRES_USER: Hastex
      POSTGRES_PASSWORD: root
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: Hastex
      POSTGRES_USER: Hastex
      POSTGRES_PASSWORD: root
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
volumes:
  postgres_data:
